name: Update Haskell Stack dependencies

on:
  schedule:
    - cron: '* * * * *'

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}
    
jobs:
    update:
        permissions:
            contents: write
            pull-requests: write
        name: Update dependencies
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          id: checkout
          uses: actions/checkout@v4

        - name: Setup Stack
          uses: haskell-actions/setup@v2
          with:
            enable-stack: true

        - name: Update stack dependencies
          id: bump-deps
          uses: stevemao/dep-haskell-stack@v1.0.0
        
        - name: Create Pull Request
          id: pr
          uses: peter-evans/create-pull-request@v5
          with:
            branch: "${{vars.AL_VERSION}}-${{steps.bump-deps.outputs.resolver}}"

        - name: Enable auto-merge for Dependabot PRs
          if: steps.pr.outputs.pull-request-url
          run: gh pr merge --auto --merge "$PR_URL"
          env:
            PR_URL: ${{steps.pr.outputs.pull-request-url}}
            GH_TOKEN: ${{ env.GITHUB_TOKEN }}
