#
name: Release new version

# Configures this workflow to run every time a pull request is merged to the branch called `main`.
on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  release-tag:
    if: github.event.pull_request.merged == true
    timeout-minutes: 5
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: write
      # 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ github.event.pull_request.head.ref }}-${{ steps.time.outputs.time }}"
          token: ${{ env.GITHUB_TOKEN }}
