name: Dependabot update AL_VERSION
on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
      - name: Update AL version
        if: steps.metadata.outputs.package-ecosystem == 'docker' && contains(steps.metadata.outputs.dependency-names, 'public.ecr.aws/lambda/provided')
        run: gh variable set AL_VERSION --body ${{steps.metadata.outputs.new-version}}
        env:
          GH_TOKEN: ${{ github.token }}
