name: Dependabot update AL_VERSION
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
      - name: Update AL version
        if: ${{ steps.metadata.outputs.package-ecosystem == 'docker' && steps.metadata.outputs.dependency-names == 'public.ecr.aws/lambda/provided' }}
        run: gh variable set AL_VERSION --body ${{steps.metadata.outputs.new-version}}
